import { PATHFINDER_SYSTEM_ID } from '@/entities/system/model/seed';
import type { SharedLibrary } from './types';

export const SEED_LIBRARY: SharedLibrary = {
  systemId: PATHFINDER_SYSTEM_ID,
  magias: [
    {
      id: 'sp-luz',
      name: 'Luz',
      school: 'Evocação',
      circle: 0,
      castTime: '1 ação padrão',
      range: 'Toque',
      duration: '10 min./nível',
      resistance: 'Nenhuma',
      desc: 'Faz um objeto brilhar como uma tocha, emitindo luz num raio de 6 m.',
    },
    {
      id: 'sp-maos-flamejantes',
      name: 'Mãos Flamejantes',
      school: 'Evocação',
      circle: 1,
      castTime: '1 ação padrão',
      range: 'Pessoal (cone de 4,5 m)',
      duration: 'Instantânea',
      resistance: 'Reflexo, metade',
      desc: 'Um leque de chamas jorra das mãos do conjurador, causando 1d4 pontos de dano de fogo por nível de conjurador (máximo 5d4) a todas as criaturas na área.',
    },
    {
      id: 'sp-detectar-magia',
      name: 'Detectar Magia',
      school: 'Adivinhação',
      circle: 0,
      castTime: '1 ação padrão',
      range: 'Pessoal',
      duration: 'Concentração, até 10 min./nível',
      resistance: 'Nenhuma',
      desc: 'Detecta auras mágicas próximas, revelando presença e intensidade de magia num cone de 18 m.',
    },
    {
      id: 'sp-escudo',
      name: 'Escudo',
      school: 'Abjuração',
      circle: 1,
      castTime: '1 ação padrão',
      range: 'Pessoal',
      duration: '1 min./nível',
      resistance: 'Nenhuma',
      desc: 'Cria uma barreira invisível à frente do conjurador, concedendo +4 de bônus de escudo na CA e imunidade a mísseis mágicos.',
    },
    {
      id: 'sp-enfeiticar-pessoa',
      name: 'Enfeitiçar Pessoa',
      school: 'Encantamento',
      circle: 1,
      castTime: '1 ação padrão',
      range: 'Médio (30 m + 3 m/nível)',
      duration: '1 hora/nível',
      resistance: 'Vontade nega',
      desc: 'Torna um humanoide amigável ao conjurador, tratando-o como um amigo de confiança.',
    },
    {
      id: 'sp-flecha-acida-persistente',
      name: 'Flecha Ácida Persistente',
      school: 'Conjuração',
      circle: 2,
      castTime: '1 ação padrão',
      range: 'Longo (114 m + 9 m/nível)',
      duration: '1 rodada + 1 rodada/nível',
      resistance: 'Nenhuma',
      desc: 'Dispara uma flecha de ácido que causa 2d4 pontos de dano no impacto e no início de cada turno do alvo até o efeito acabar ou o ácido ser neutralizado.',
    },
    {
      id: 'sp-consertar',
      name: 'Consertar',
      school: 'Transmutação',
      circle: 0,
      castTime: '1 minuto',
      range: 'Toque',
      duration: 'Instantânea',
      resistance: 'Vontade nega (objeto inofensivo)',
      desc: 'Repara um único item quebrado, desde que não seja mágico.',
    },
    {
      id: 'sp-orientacao',
      name: 'Orientação',
      school: 'Adivinhação',
      circle: 0,
      castTime: '1 ação padrão',
      range: 'Toque',
      duration: '1 minuto',
      resistance: 'Vontade nega (inofensivo)',
      desc: 'Concede +1 de bônus de intuição num único teste de perícia ou de ataque à sua escolha.',
    },
    {
      id: 'sp-curar-ferimentos-leves',
      name: 'Curar Ferimentos Leves',
      school: 'Cura',
      circle: 1,
      castTime: '1 ação padrão',
      range: 'Toque',
      duration: 'Instantânea',
      resistance: 'Vontade metade (inofensivo)',
      desc: 'Cura 1d8 pontos de dano +1 por nível de conjurador (máximo +5).',
    },
    {
      id: 'sp-bencao',
      name: 'Bênção',
      school: 'Encantamento',
      circle: 1,
      castTime: '1 ação padrão',
      range: 'Área (raio de 15 m centrado no conjurador)',
      duration: '1 minuto/nível',
      resistance: 'Nenhuma',
      desc: 'Concede +1 nas jogadas de ataque e testes de resistência contra medo a todos os aliados na área.',
    },
    {
      id: 'sp-bola-de-fogo',
      name: 'Bola de Fogo',
      school: 'Evocação',
      circle: 3,
      castTime: '1 ação padrão',
      range: 'Longo (114 m + 9 m/nível)',
      duration: 'Instantânea',
      resistance: 'Reflexo, metade',
      desc: 'Um raio flamejante parte do dedo do conjurador até um ponto à sua escolha, explodindo em uma bola de fogo que causa 1d6 pontos de dano de fogo por nível de conjurador (máximo 10d6) a todas as criaturas em um raio de 6 metros.',
    },
    {
      id: 'sp-bola-de-fogo-retardada',
      name: 'Bola de Fogo Retardada',
      school: 'Evocação',
      circle: 3,
      castTime: '1 ação padrão',
      range: 'Longo (114 m + 9 m/nível)',
      duration: 'Até 5 rodadas',
      resistance: 'Reflexo, metade',
      desc: 'Como Bola de Fogo, mas a detonação pode ser adiada por até 5 rodadas.',
    },
  ],
  talentos: [
    {
      id: 'ft-ataque-poderoso',
      name: 'Ataque Poderoso',
      desc: 'Pré-requisito: For 13. Troca precisão por dano corpo a corpo.',
      tag: 'Combate',
    },
    {
      id: 'ft-esquiva',
      name: 'Esquiva',
      desc: '+1 de esquiva na CA contra um oponente designado.',
      tag: 'Geral',
    },
    {
      id: 'ft-iniciativa-aprimorada',
      name: 'Iniciativa Aprimorada',
      desc: '+4 nos testes de iniciativa.',
      tag: 'Combate',
    },
    {
      id: 'ft-foco-magia-evocacao',
      name: 'Foco em Magia (Evocação)',
      desc: '+1 na CD de resistência de magias da escola de Evocação.',
      tag: 'Geral',
    },
    {
      id: 'ft-conjuracao-extra-1',
      name: 'Conjuração Extra (magia 1º círc.)',
      desc: 'Pré-requisito: Feiticeira nível 1. Ganha um espaço extra de 1º círculo.',
      tag: 'Metamagia',
    },
  ],
  pericias: [
    {
      id: 'sk-acrobacia',
      name: 'Acrobacia',
      desc: 'Destreza · usada para manter o equilíbrio e evitar quedas',
      tag: 'Fixa',
    },
    {
      id: 'sk-percepcao',
      name: 'Percepção',
      desc: 'Sabedoria · notar detalhes e criaturas escondidas',
      tag: 'Fixa',
    },
    {
      id: 'sk-diplomacia',
      name: 'Diplomacia',
      desc: 'Carisma · negociar e mudar atitudes',
      tag: 'Fixa',
    },
    {
      id: 'sk-furtividade',
      name: 'Furtividade',
      desc: 'Destreza · mover-se sem ser notado',
      tag: 'Fixa',
    },
    {
      id: 'sk-conhecimento-arcano',
      name: 'Conhecimento (arcano)',
      desc: 'Inteligência · treinada · magias, itens e criaturas mágicas',
      tag: 'Treinada',
    },
  ],
  habilidades: [
    {
      id: 'sa-canalizar-energia',
      name: 'Canalizar Energia',
      subtitle: 'Habilidade de clériga',
      uses: '',
      desc: 'Emite uma onda de energia positiva ou negativa em área, curando aliados ou ferindo mortos-vivos.',
    },
    {
      id: 'sa-furia-elfica',
      name: 'Fúria Élfica',
      subtitle: 'Efeito racial de sangue feérico',
      uses: '',
      desc: 'Concede acesso a uma habilidade similar a magia ligada à linhagem feérica do personagem.',
    },
    {
      id: 'sa-visao-escuro',
      name: 'Visão no Escuro',
      subtitle: 'Traço racial · 18 m',
      uses: '',
      desc: 'Vê no escuro até 18 m em preto e branco.',
    },
    {
      id: 'sa-detectar-bem-mal',
      name: 'Detectar Bem/Mal',
      subtitle: 'Habilidade de classe',
      uses: 'à vontade',
      desc: 'Detecta criaturas de alinhamento oposto à vontade.',
    },
    {
      id: 'sa-graca-divina',
      name: 'Graça Divina',
      subtitle: 'Paladino nível 2',
      uses: '',
      desc: 'Soma o bônus de Carisma a todos os testes de resistência.',
    },
    {
      id: 'sa-esquiva-sobrenatural',
      name: 'Esquiva Sobrenatural',
      subtitle: 'Ladino nível 4',
      uses: '',
      desc: 'Mantém o bônus de Destreza na CA mesmo surpreendido.',
    },
    {
      id: 'sa-furia',
      name: 'Fúria',
      subtitle: 'Bárbaro nível 1',
      uses: 'rodadas/dia',
      desc: 'Entra em fúria ganhando bônus em For e Con e −2 na CA.',
    },
    {
      id: 'sa-imunidade-sono',
      name: 'Imunidade a Sono',
      subtitle: 'Traço racial de meio-elfo',
      uses: '',
      desc: 'Meio-elfos não dormem magicamente e são imunes a efeitos de sono.',
    },
  ],
  armas: [
    {
      id: 'wp-rapiete',
      name: 'Rapiete',
      atk: '+0',
      crit: '19-20/x2',
      dmg: '1d6',
      type: 'Perfurante',
      range: '—',
      desc: '',
      hasAmmo: false,
      ammoMax: 0,
    },
    {
      id: 'wp-funda',
      name: 'Funda',
      atk: '+0',
      crit: 'x2',
      dmg: '1d4',
      type: 'Concussão',
      range: '15 m',
      desc: '',
      hasAmmo: true,
      ammoMax: 20,
    },
    {
      id: 'wp-espada-longa',
      name: 'Espada Longa',
      atk: '+0',
      crit: '19-20/x2',
      dmg: '1d8',
      type: 'Cortante',
      range: '—',
      desc: '',
      hasAmmo: false,
      ammoMax: 0,
    },
    {
      id: 'wp-arco-curto',
      name: 'Arco Curto',
      atk: '+0',
      crit: 'x3',
      dmg: '1d6',
      type: 'Perfurante',
      range: '18 m',
      desc: '',
      hasAmmo: true,
      ammoMax: 20,
    },
    {
      id: 'wp-besta-leve',
      name: 'Besta Leve',
      atk: '+0',
      crit: '19-20/x2',
      dmg: '1d8',
      type: 'Perfurante',
      range: '24 m',
      desc: '',
      hasAmmo: true,
      ammoMax: 10,
    },
    {
      id: 'wp-machado-guerra',
      name: 'Machado de Guerra',
      atk: '+0',
      crit: 'x3',
      dmg: '1d10',
      type: 'Cortante',
      range: '—',
      desc: '',
      hasAmmo: false,
      ammoMax: 0,
    },
  ],
  idiomas: [
    { id: 'lg-comum', name: 'Comum', desc: 'Idioma universal do continente', tag: 'Idioma' },
    { id: 'lg-elfico', name: 'Élfico', desc: 'Falado pelos elfos e meio-elfos', tag: 'Idioma' },
    { id: 'lg-celestial', name: 'Celestial', desc: 'Idioma dos planos superiores', tag: 'Idioma' },
    { id: 'lg-anao', name: 'Anão', desc: 'Falado pelos anões', tag: 'Idioma' },
    { id: 'lg-orquico', name: 'Órquico', desc: 'Falado por orcs e meio-orcs', tag: 'Idioma' },
    {
      id: 'lg-draconico',
      name: 'Dracônico',
      desc: 'Idioma dos dragões e criaturas répteis',
      tag: 'Idioma',
    },
    { id: 'lg-abissal', name: 'Abissal', desc: 'Idioma dos demônios', tag: 'Idioma' },
    { id: 'lg-gigante', name: 'Gigante', desc: 'Falado por gigantes e ogros', tag: 'Idioma' },
  ],
  criaturas: [
    { id: 'cr-goblin', name: 'Goblin', desc: 'ND 1/3 · humanoide pequeno', tag: 'Criatura' },
    { id: 'cr-lobo', name: 'Lobo', desc: 'ND 1 · animal médio', tag: 'Criatura' },
    { id: 'cr-esqueleto', name: 'Esqueleto', desc: 'ND 1/3 · morto-vivo médio', tag: 'Criatura' },
  ],
};
